//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace caClient.caServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="caServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Connect", ReplyAction="http://tempuri.org/IService/ConnectResponse")]
        caCoreLibrary.caMessage Connect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMessages", ReplyAction="http://tempuri.org/IService/GetMessagesResponse")]
        System.Collections.Generic.List<caCoreLibrary.caMessage> GetMessages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetParticipantRelationAnalysisResultList", ReplyAction="http://tempuri.org/IService/GetParticipantRelationAnalysisResultListResponse")]
        System.Collections.Generic.List<caCoreLibrary.caRelationAnalysisResult> GetParticipantRelationAnalysisResultList(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetFlowAnalysisResultList", ReplyAction="http://tempuri.org/IService/GetFlowAnalysisResultListResponse")]
        System.Collections.Generic.List<caCoreLibrary.caFlowAnalysisResult> GetFlowAnalysisResultList(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTagParticipantAnalysisResultList", ReplyAction="http://tempuri.org/IService/GetTagParticipantAnalysisResultListResponse")]
        System.Collections.Generic.List<caCoreLibrary.caTagParticipantAnalysisResult> GetTagParticipantAnalysisResultList(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoadParticipant", ReplyAction="http://tempuri.org/IService/LoadParticipantResponse")]
        caCoreLibrary.caParticipant LoadParticipant(string _participantId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SaveParticipant", ReplyAction="http://tempuri.org/IService/SaveParticipantResponse")]
        caCoreLibrary.caParticipant SaveParticipant(caCoreLibrary.caParticipant actualP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoadParticipantGroups", ReplyAction="http://tempuri.org/IService/LoadParticipantGroupsResponse")]
        System.Collections.Generic.List<caCoreLibrary.caParticipant> LoadParticipantGroups(string _participantId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SaveParticipantGroups", ReplyAction="http://tempuri.org/IService/SaveParticipantGroupsResponse")]
        System.Collections.Generic.List<caCoreLibrary.caParticipant> SaveParticipantGroups(string _participantId, System.Collections.Generic.List<string> groups);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoadParticipantMembers", ReplyAction="http://tempuri.org/IService/LoadParticipantMembersResponse")]
        System.Collections.Generic.List<caCoreLibrary.caParticipant> LoadParticipantMembers(string _participantId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SaveParticipantMembers", ReplyAction="http://tempuri.org/IService/SaveParticipantMembersResponse")]
        System.Collections.Generic.List<caCoreLibrary.caParticipant> SaveParticipantMembers(string _participantId, System.Collections.Generic.List<string> members);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoadParticipantAddress", ReplyAction="http://tempuri.org/IService/LoadParticipantAddressResponse")]
        System.Collections.Generic.List<caCoreLibrary.caParticipantAddress> LoadParticipantAddress(string _participantId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SaveParticipantAddress", ReplyAction="http://tempuri.org/IService/SaveParticipantAddressResponse")]
        System.Collections.Generic.List<caCoreLibrary.caParticipantAddress> SaveParticipantAddress(string _participantId, System.Collections.Generic.List<caCoreLibrary.caParticipantAddress> address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoadParticipantList", ReplyAction="http://tempuri.org/IService/LoadParticipantListResponse")]
        System.Collections.Generic.List<caCoreLibrary.caParticipant> LoadParticipantList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ReplaceParticipant", ReplyAction="http://tempuri.org/IService/ReplaceParticipantResponse")]
        caCoreLibrary.caMessage ReplaceParticipant(string _fromPID, string _toPID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoadTagList", ReplyAction="http://tempuri.org/IService/LoadTagListResponse")]
        System.Collections.Generic.List<string> LoadTagList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RunTaggingRule", ReplyAction="http://tempuri.org/IService/RunTaggingRuleResponse")]
        caCoreLibrary.caMessage RunTaggingRule(string _ruleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTag", ReplyAction="http://tempuri.org/IService/DeleteTagResponse")]
        caCoreLibrary.caMessage DeleteTag(string _tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoadTaggingRule", ReplyAction="http://tempuri.org/IService/LoadTaggingRuleResponse")]
        caCoreLibrary.caTaggingRule LoadTaggingRule(string _ruleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoadTaggingRuleList", ReplyAction="http://tempuri.org/IService/LoadTaggingRuleListResponse")]
        System.Collections.Generic.List<caCoreLibrary.caTaggingRule> LoadTaggingRuleList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SaveTaggingRule", ReplyAction="http://tempuri.org/IService/SaveTaggingRuleResponse")]
        caCoreLibrary.caTaggingRule SaveTaggingRule(caCoreLibrary.caTaggingRule tr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IServiceChannel : caClient.caServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<caClient.caServiceReference.IService>, caClient.caServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public caCoreLibrary.caMessage Connect() {
            return base.Channel.Connect();
        }
        
        public System.Collections.Generic.List<caCoreLibrary.caMessage> GetMessages() {
            return base.Channel.GetMessages();
        }
        
        public System.Collections.Generic.List<caCoreLibrary.caRelationAnalysisResult> GetParticipantRelationAnalysisResultList(string query) {
            return base.Channel.GetParticipantRelationAnalysisResultList(query);
        }
        
        public System.Collections.Generic.List<caCoreLibrary.caFlowAnalysisResult> GetFlowAnalysisResultList(string query) {
            return base.Channel.GetFlowAnalysisResultList(query);
        }
        
        public System.Collections.Generic.List<caCoreLibrary.caTagParticipantAnalysisResult> GetTagParticipantAnalysisResultList(string query) {
            return base.Channel.GetTagParticipantAnalysisResultList(query);
        }
        
        public caCoreLibrary.caParticipant LoadParticipant(string _participantId) {
            return base.Channel.LoadParticipant(_participantId);
        }
        
        public caCoreLibrary.caParticipant SaveParticipant(caCoreLibrary.caParticipant actualP) {
            return base.Channel.SaveParticipant(actualP);
        }
        
        public System.Collections.Generic.List<caCoreLibrary.caParticipant> LoadParticipantGroups(string _participantId) {
            return base.Channel.LoadParticipantGroups(_participantId);
        }
        
        public System.Collections.Generic.List<caCoreLibrary.caParticipant> SaveParticipantGroups(string _participantId, System.Collections.Generic.List<string> groups) {
            return base.Channel.SaveParticipantGroups(_participantId, groups);
        }
        
        public System.Collections.Generic.List<caCoreLibrary.caParticipant> LoadParticipantMembers(string _participantId) {
            return base.Channel.LoadParticipantMembers(_participantId);
        }
        
        public System.Collections.Generic.List<caCoreLibrary.caParticipant> SaveParticipantMembers(string _participantId, System.Collections.Generic.List<string> members) {
            return base.Channel.SaveParticipantMembers(_participantId, members);
        }
        
        public System.Collections.Generic.List<caCoreLibrary.caParticipantAddress> LoadParticipantAddress(string _participantId) {
            return base.Channel.LoadParticipantAddress(_participantId);
        }
        
        public System.Collections.Generic.List<caCoreLibrary.caParticipantAddress> SaveParticipantAddress(string _participantId, System.Collections.Generic.List<caCoreLibrary.caParticipantAddress> address) {
            return base.Channel.SaveParticipantAddress(_participantId, address);
        }
        
        public System.Collections.Generic.List<caCoreLibrary.caParticipant> LoadParticipantList() {
            return base.Channel.LoadParticipantList();
        }
        
        public caCoreLibrary.caMessage ReplaceParticipant(string _fromPID, string _toPID) {
            return base.Channel.ReplaceParticipant(_fromPID, _toPID);
        }
        
        public System.Collections.Generic.List<string> LoadTagList() {
            return base.Channel.LoadTagList();
        }
        
        public caCoreLibrary.caMessage RunTaggingRule(string _ruleId) {
            return base.Channel.RunTaggingRule(_ruleId);
        }
        
        public caCoreLibrary.caMessage DeleteTag(string _tag) {
            return base.Channel.DeleteTag(_tag);
        }
        
        public caCoreLibrary.caTaggingRule LoadTaggingRule(string _ruleId) {
            return base.Channel.LoadTaggingRule(_ruleId);
        }
        
        public System.Collections.Generic.List<caCoreLibrary.caTaggingRule> LoadTaggingRuleList() {
            return base.Channel.LoadTaggingRuleList();
        }
        
        public caCoreLibrary.caTaggingRule SaveTaggingRule(caCoreLibrary.caTaggingRule tr) {
            return base.Channel.SaveTaggingRule(tr);
        }
    }
}
