REM INSERTING into CAD_PARTICIPANT
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0','Unknown User','Unknown',0,1,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('G0','Unknown Group','Unknown',1,1,null);
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-muratiakos@yahoo.co.uk','Muráti Ákos',null,0,3,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-info@goe.hu','GOE iroda',null,0,1,'5b0a037b-9abf-48e1-af11-9c7af90a3477');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-csaba.radnothy@bud.ahh.gov.hu','Radnóthy Csaba',null,0,1,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-hknews-admin@vik-hk.bme.hu',' (hknews-admin@vik-hk.bme.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-hknews@vik-hk.bme.hu','null (hknews@vik-hk.bme.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-tundecsenge@yahoo.co.uk',' (tundecsenge@yahoo.co.uk)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-ncsaba@freemail.hu','Csaba "Németh" (ncsaba@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-kicsitmas@freemail.hu','Zsófi (kicsitmas@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-uttam_devi@yahoo.com','Uta Friedrich (uttam_devi@yahoo.com)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-yvy@tvnetwork.hu','Ivett Jagodics (yvy@tvnetwork.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-cotutpnl@axelero.hu','"Bangó" Jani (cotutpnl@axelero.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-bme.adams@gmail.com',' (bme.adams@gmail.com)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-sz__g@freemail.hu',' (sz__g@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-cach.king@gmail.com',' (cach.king@gmail.com)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-z.anett@vipmail.hu','Zérczi Anett (z.anett@vipmail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-zsvick@wap.hu','Zsoldos Viktor (zsvick@wap.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-renatas@freemail.hu','Szöllõsi Renáta (renatas@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-gyapjas21@vipmail.hu','Szirom Anna (gyapjas21@vipmail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-eviszi@citromail.hu','Szilágyi Éva (eviszi@citromail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-szeredib@freemail.hu','Szeredi Balázs (szeredib@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-szedzsi@axelero.hu','Szegedi Tamás (szedzsi@axelero.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-szabovirag18@freemail.hu','Szabó Virág (szabovirag18@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-poofee@citromail.hu','Szabó Balázs Márton (poofee@citromail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-sft@vipmail.hu','Schmikl Tamás (sft@vipmail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-schidi@freemail.hu','null (schidi@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-poofee@gmail.com','Poofee (poofee@gmail.com)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-odjag@freemail.hu','Petróczi Attila (odjag@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-killswitchengage@freemail.hu','Nagy Gergely (killswitchengage@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-molgi@freemail.hu','Molnár Ági (molgi@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-mariannhm@freemail.hu','null (mariannhm@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-meli@sch.bme.hu','Meli (meli@sch.bme.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-m.kovacs@uniprint.hu','Kovács Mariann (m.kovacs@uniprint.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-fredo67@axelero.hu','Kovács Róbert (fredo67@axelero.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-tututututu@freemail.hu','Kotsy Roland (tututututu@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-tpeti@sch.bme.hu','Kond (tpeti@sch.bme.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-ksiskot@gmail.com','Kocsis Balázs (ksiskot@gmail.com)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-kervery@freemail.hu','Kertész Veronika (kervery@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-v.kalmar@auchan.hu','Kalmár Viktória (v.kalmar@auchan.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-huzsuzsa@freemail.hu','Huczmann Zsuzsanna (huzsuzsa@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-mhori@freemail.hu','Horváth Mária (mhori@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-gaspar.attila@lanten.hu','Gáspár Attila (gaspar.attila@lanten.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-azeroths@gmail.com','Gyulavári Ádám (azeroths@gmail.com)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-foldiroland@freemail.hu','Földi Roland (foldiroland@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-freilusz@freemail.hu','Freiler Zsolt (freilusz@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-flamisg@axelero.hu','Flamis Gábor (flamisg@axelero.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-maryannef@freemail.hu','File Marianna (maryannef@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-dbandris@freemail.hu','Dombai András (dbandris@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-debrei.tamas@gmail.com','Debrei Tamás (debrei.tamas@gmail.com)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-lioness.55@freemail.hu','Darabos Judit (lioness.55@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-csalaig@freemail.hu','Csalai Gábor (csalaig@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-sophy4444@freemail.hu','Buga Zsófi (sophy4444@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-titkarsag@degrt.hu','Bozó Brigi (titkarsag@degrt.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-boriszt@freemail.hu','Borisz Tímea (boriszt@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-pocok60@freemail.hu','Boda Györgyi (pocok60@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-csibenyul@freemail.hu','Barbi (csibenyul@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-kiwi2002@freemail.hu','Balint Bartfai (kiwi2002@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-alpijoe@gmail.com','Alpar Bors (alpijoe@gmail.com)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-7abszint@sch.bme.hu','null (7abszint@sch.bme.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-dp304@hszk.bme.hu','null (dp304@hszk.bme.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-tdavid@dsys.hu','Tamásy Dávid',null,0,1,'30cd1a62-1d89-4d5d-9bc0-74af086eb31a');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-szjoe5@freemail.hu','null (szjoe5@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-kisker@starcopy.hu','null (kisker@starcopy.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-tarnaigy@westel900.net','null (tarnaigy@westel900.net)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-tarnaigy@mail.tvnet.hu','Tarnay György (tarnaigy@mail.tvnet.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-abascadiv@gmail.com','Vida Csaba',null,0,1,'047e003e-807b-4782-9240-922afe1fbdad');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-posa.gabriella@morpho.hu','null (posa.gabriella@morpho.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-kyrus20@hotmail.com','Pálfy Kyra',null,0,1,'047e003e-807b-4782-9240-922afe1fbdad');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-hfgen@iit.bme.hu',' (hfgen@iit.bme.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-kriszmusz@hotmail.com','kriszmusz@hotmail.com (kriszmusz@hotmail.com)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-abascadiv@freemail.hu','Csaba Vida (abascadiv@freemail.hu)',null,0,3,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-szeledit@freemail.hu','Murátiné Szél Edit','szeledit',0,1,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-eszel@vipmail.hu',' (eszel@vipmail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-schulcz@hit.bme.hu',' (schulcz@hit.bme.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-roncsautokft@roncsautokft.hu','Roncs Autó Kft',null,0,0,'30cd1a62-1d89-4d5d-9bc0-74af086eb31a');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-szjoe5@gmail.com','József Szeles (szjoe5@gmail.com)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-muratiakos@hotmail.com',' (muratiakos@hotmail.com)',null,0,3,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-muratiakos@gmail.com','null (muratiakos@gmail.com)',null,0,3,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-csradnothy@enternet.hu',' (csradnothy@enternet.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-peter.bardos@gmail.com',' (peter.bardos@gmail.com)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-akos.deliaga@gmail.com',' (akos.deliaga@gmail.com)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-konfar.andras@freemail.hu','null (konfar.andras@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-jarod@vipmail.hu','null (jarod@vipmail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-deliaga@freemail.hu','null (deliaga@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-tree@ak47.hu','null (tree@ak47.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('U0-trii@freemail.hu','null (trii@freemail.hu)',null,0,0,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('acc53047-2897-4ec7-9796-bb3b6f7cf7d0','Muráti Ákos','AMurati',0,1,'d7c5aef0-b361-4b9a-a918-d4c940081897');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('d7c5aef0-b361-4b9a-a918-d4c940081897','Muráti Család',null,1,1,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('30cd1a62-1d89-4d5d-9bc0-74af086eb31a','Munka',null,1,1,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('047e003e-807b-4782-9240-922afe1fbdad','Barátok',null,1,1,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('5b0a037b-9abf-48e1-af11-9c7af90a3477','Autósok',null,1,1,'G0');
Insert into CAD_PARTICIPANT (PARTICIPANT_ID,NAME,FOREIGN_ID,TYPE,STATUS,PRIMARY_GROUP) values ('b169b47e-fb13-49f2-ad05-053e6a255f72','murati.hu domain',null,1,1,'G0');
