REM INSERTING into CAL_SUBCATEGORY
Insert into CAL_SUBCATEGORY (ID,CATEGORY,NAME) values (0,0,'TO');
Insert into CAL_SUBCATEGORY (ID,CATEGORY,NAME) values (1,0,'CC');
Insert into CAL_SUBCATEGORY (ID,CATEGORY,NAME) values (2,0,'BCC');
Insert into CAL_SUBCATEGORY (ID,CATEGORY,NAME) values (3,1,'Phone');
Insert into CAL_SUBCATEGORY (ID,CATEGORY,NAME) values (4,1,'VOIP');
Insert into CAL_SUBCATEGORY (ID,CATEGORY,NAME) values (5,2,'SMS');
