-- ****** Object: Table EMA_ADMIN.CAD_PARTICIPANT Script Date: 2010.05.11. 6:27:45 ******
CREATE TABLE "CAD_PARTICIPANT" (
  "PRIMARY_GROUP" VARCHAR2(400 BYTE) DEFAULT 'G0',
  "PARTICIPANT_ID" VARCHAR2(400 BYTE),
  "NAME" VARCHAR2(400 BYTE),
  "FOREIGN_ID" VARCHAR2(100 BYTE),
  "TYPE" NUMBER(1,0) DEFAULT 0,
  "STATUS" NUMBER(1,0) DEFAULT 0);
CREATE UNIQUE INDEX "P_PID_PK"
  ON "CAD_PARTICIPANT" ( 
    "PARTICIPANT_ID");
ALTER TABLE "CAD_PARTICIPANT" ADD ( 
  CONSTRAINT "P_PID_PK" 
    PRIMARY KEY ( "PARTICIPANT_ID") 
    USING INDEX "P_PID_PK" 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_PARTICIPANT" ADD ( 
  CONSTRAINT "P_TYPE_NN" 
    CHECK ( "TYPE" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_PARTICIPANT" ADD ( 
  CONSTRAINT "P_NAME_NN" 
    CHECK ( "NAME" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_PARTICIPANT" ADD ( 
  CONSTRAINT "P_PID_NN" 
    CHECK ( "PARTICIPANT_ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_PARTICIPANT" ADD ( 
  CONSTRAINT "P_STATUS_NN" 
    CHECK ( "STATUS" IS NOT NULL) 
    ENABLE 
    VALIDATE );
-- ****** Object: Table EMA_ADMIN.CAD_PARTICIPANTRELATION Script Date: 2010.05.11. 6:27:52 ******
CREATE TABLE "CAD_PARTICIPANTRELATION" (
  "ACTIVE" NUMBER(1,0) DEFAULT 1,
  "MEMBER_FROM" DATE,
  "MEMBER_TILL" DATE,
  "USER_ID" VARCHAR2(400 BYTE),
  "GROUP_ID" VARCHAR2(400 BYTE));
CREATE UNIQUE INDEX "PR_RECORD_U"
  ON "CAD_PARTICIPANTRELATION" ( 
    "GROUP_ID", 
    "USER_ID");
ALTER TABLE "CAD_PARTICIPANTRELATION" ADD ( 
  CONSTRAINT "PR_FK_GROUP" 
    FOREIGN KEY ( "GROUP_ID")
       REFERENCES "CAD_PARTICIPANT" ( "PARTICIPANT_ID") 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_PARTICIPANTRELATION" ADD ( 
  CONSTRAINT "PR_FK_USER" 
    FOREIGN KEY ( "USER_ID")
       REFERENCES "CAD_PARTICIPANT" ( "PARTICIPANT_ID") 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_PARTICIPANTRELATION" ADD ( 
  CONSTRAINT "PR_ACT_NN" 
    CHECK ( "ACTIVE" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_PARTICIPANTRELATION" ADD ( 
  CONSTRAINT "PR_RECORD_U" 
    UNIQUE ( "GROUP_ID", "USER_ID") 
    USING INDEX "PR_RECORD_U" 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_PARTICIPANTRELATION" ADD ( 
  CONSTRAINT "PR_GID_NN" 
    CHECK ( "GROUP_ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_PARTICIPANTRELATION" ADD ( 
  CONSTRAINT "PR_UID_NN" 
    CHECK ( "USER_ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
-- ****** Object: Table EMA_ADMIN.CAD_THREAD Script Date: 2010.05.11. 6:27:53 ******
CREATE TABLE "CAD_THREAD" (
  "THREAD_ID" VARCHAR2(400 BYTE) DEFAULT NULL,
  "NAME" VARCHAR2(400 BYTE) DEFAULT NULL);
CREATE UNIQUE INDEX "TH_TID_PK"
  ON "CAD_THREAD" ( 
    "THREAD_ID");
ALTER TABLE "CAD_THREAD" ADD ( 
  CONSTRAINT "TH_TID_PK" 
    PRIMARY KEY ( "THREAD_ID") 
    USING INDEX "TH_TID_PK" 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_THREAD" ADD ( 
  CONSTRAINT "TH_NAME_NN" 
    CHECK ( "NAME" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_THREAD" ADD ( 
  CONSTRAINT "TH_TID_NN" 
    CHECK ( "THREAD_ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
-- ****** Object: Table EMA_ADMIN.CAL_CATEGORY Script Date: 2010.05.11. 6:27:53 ******
CREATE TABLE "CAL_CATEGORY" (
  "ID" NUMBER,
  "NAME" VARCHAR2(20 BYTE));
ALTER TABLE "CAL_CATEGORY" ADD ( 
  CONSTRAINT "SYS_C004066" 
    CHECK ( "NAME" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAL_CATEGORY" ADD ( 
  CONSTRAINT "SYS_C004065" 
    CHECK ( "ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
-- ****** Object: Table EMA_ADMIN.CAL_SUBCATEGORY Script Date: 2010.05.11. 6:27:53 ******
CREATE TABLE "CAL_SUBCATEGORY" (
  "ID" NUMBER,
  "CATEGORY" NUMBER,
  "NAME" VARCHAR2(20 BYTE));
ALTER TABLE "CAL_SUBCATEGORY" ADD ( 
  CONSTRAINT "SYS_C004069" 
    CHECK ( "NAME" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAL_SUBCATEGORY" ADD ( 
  CONSTRAINT "SYS_C004068" 
    CHECK ( "CATEGORY" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAL_SUBCATEGORY" ADD ( 
  CONSTRAINT "SYS_C004067" 
    CHECK ( "ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
-- ****** Object: Table EMA_ADMIN.CAD_SUBCOMM Script Date: 2010.05.11. 6:27:53 ******
CREATE TABLE "CAD_SUBCOMM" (
  "SUBCOMM_ID" VARCHAR2(40 CHAR),
  "CATEGORY" NUMBER(1,0) DEFAULT 0,
  "SUBCATEGORY" NUMBER(1,0) DEFAULT 0,
  "RESULT" NUMBER(1,0) DEFAULT 1,
  "FROM_PARTICIPANT" VARCHAR2(400 BYTE),
  "TO_PARTICIPANT" VARCHAR2(400 BYTE),
  "SENT_TIME" DATE,
  "RECEIVED_TIME" DATE,
  "JOINT_SEC" NUMBER DEFAULT 0,
  "DURATION_SEC" NUMBER DEFAULT 0,
  "COMM_ID" VARCHAR2(400 BYTE),
  "PREV_COMM_ID" VARCHAR2(400 BYTE),
  "PREV_DELAY_SEC" NUMBER(10,0),
  "PREV_LINKMODE" NUMBER(1,0) DEFAULT 0,
  "THREAD_ID" VARCHAR2(400 BYTE),
  "DATE_KEY" NUMBER(8,0),
  "TIME_KEY" NUMBER(6,0));
CREATE UNIQUE INDEX "SC_SCID_PK"
  ON "CAD_SUBCOMM" ( 
    "SUBCOMM_ID");
CREATE INDEX "SC_CID"
  ON "CAD_SUBCOMM" ( 
    "COMM_ID");
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_FK_DATE" 
    FOREIGN KEY ( "DATE_KEY")
       REFERENCES "CAD_DATE" ( "DATE_KEY") 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_FK_THREAD" 
    FOREIGN KEY ( "THREAD_ID")
       REFERENCES "CAD_THREAD" ( "THREAD_ID") 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_FK_TIME" 
    FOREIGN KEY ( "TIME_KEY")
       REFERENCES "CAD_TIME" ( "TIME_KEY") 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_FK_FROM" 
    FOREIGN KEY ( "FROM_PARTICIPANT")
       REFERENCES "CAD_PARTICIPANT" ( "PARTICIPANT_ID") 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_FK_TO" 
    FOREIGN KEY ( "TO_PARTICIPANT")
       REFERENCES "CAD_PARTICIPANT" ( "PARTICIPANT_ID") 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_FK_COMM" 
    FOREIGN KEY ( "COMM_ID")
       REFERENCES "CAD_COMM" ( "COMM_ID") 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_THREAD_NN" 
    CHECK ( "THREAD_ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_TIMEKEY_NN" 
    CHECK ( "TIME_KEY" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_DATEKEY_NN" 
    CHECK ( "DATE_KEY" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_SENT_NN" 
    CHECK ( "SENT_TIME" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_SCID_PK" 
    PRIMARY KEY ( "SUBCOMM_ID") 
    USING INDEX "SC_SCID_PK" 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_TO_P_NN" 
    CHECK ( "TO_PARTICIPANT" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_FP_NN" 
    CHECK ( "FROM_PARTICIPANT" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_RESULT_NN" 
    CHECK ( "RESULT" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_SUBCAT_NN" 
    CHECK ( "SUBCATEGORY" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_CAT_NN" 
    CHECK ( "CATEGORY" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_SUBCOMM" ADD ( 
  CONSTRAINT "SC_SCID_NN" 
    CHECK ( "SUBCOMM_ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
-- ****** Object: Table EMA_ADMIN.CAD_STAT Script Date: 2010.05.11. 6:27:53 ******
CREATE TABLE "CAD_STAT" (
  "STAT_ID" VARCHAR2(20 BYTE),
  "STAT_TIME" VARCHAR2(20 BYTE),
  "STAT_OBJECT" VARCHAR2(20 BYTE),
  "STAT_TYPE" VARCHAR2(20 BYTE),
  "COUNT_TOUCH" VARCHAR2(20 BYTE),
  "AVG_DURATION" VARCHAR2(20 BYTE),
  "MIN_DURATION" VARCHAR2(20 BYTE),
  "MAX_DURATION" VARCHAR2(20 BYTE),
  "COUNT_DELAY" VARCHAR2(20 BYTE),
  "AVG_DELAY" VARCHAR2(20 BYTE),
  "MIN_DELAY" VARCHAR2(20 BYTE),
  "MAX_DELAY" VARCHAR2(20 BYTE));
-- ****** Object: Table EMA_ADMIN.CAS_QUERY Script Date: 2010.05.11. 6:27:53 ******
CREATE TABLE "CAS_QUERY" (
  "ID" VARCHAR2(400 BYTE),
  "NAME" VARCHAR2(400 BYTE),
  "QUERY" CLOB);
ALTER TABLE "CAS_QUERY" ADD ( 
  CONSTRAINT "SYS_C004139" 
    CHECK ( "NAME" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAS_QUERY" ADD ( 
  CONSTRAINT "SYS_C004138" 
    CHECK ( "ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
-- ****** Object: Table EMA_ADMIN.CAL_RAWSTATUS Script Date: 2010.05.11. 6:27:53 ******
CREATE TABLE "CAL_RAWSTATUS" (
  "ID" NUMBER,
  "NAME" VARCHAR2(20 BYTE));
ALTER TABLE "CAL_RAWSTATUS" ADD ( 
  CONSTRAINT "SYS_C004071" 
    CHECK ( "NAME" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAL_RAWSTATUS" ADD ( 
  CONSTRAINT "SYS_C004070" 
    CHECK ( "ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
-- ****** Object: Table EMA_ADMIN.CAD_RAWDATA Script Date: 2010.05.11. 6:27:53 ******
CREATE TABLE "CAD_RAWDATA" (
  "COMM_ID" VARCHAR2(400 BYTE),
  "BUFFER_ID" VARCHAR2(400 BYTE),
  "DATA" CLOB,
  "STATUS" NUMBER(1,0) DEFAULT 0,
  "CATEGORY" NUMBER(1,0) DEFAULT 0);
CREATE UNIQUE INDEX "RD_BID_U"
  ON "CAD_RAWDATA" ( 
    "BUFFER_ID");
CREATE INDEX "RD_CID_I"
  ON "CAD_RAWDATA" ( 
    "COMM_ID");
ALTER TABLE "CAD_RAWDATA" ADD ( 
  CONSTRAINT "RD_CAT_NN" 
    CHECK ( "CATEGORY" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_RAWDATA" ADD ( 
  CONSTRAINT "RD_BID_U" 
    UNIQUE ( "BUFFER_ID") 
    USING INDEX "RD_BID_U" 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_RAWDATA" ADD ( 
  CONSTRAINT "RD_STATUS_NN" 
    CHECK ( "STATUS" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_RAWDATA" ADD ( 
  CONSTRAINT "RD_BID_NN" 
    CHECK ( "BUFFER_ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
-- ****** Object: Table EMA_ADMIN.CAD_KEYWORD Script Date: 2010.05.11. 6:27:53 ******
CREATE TABLE "CAD_KEYWORD" (
  "COMM_ID" VARCHAR2(400 BYTE),
  "KEYWORD" VARCHAR2(400 BYTE));
CREATE UNIQUE INDEX "CK_RECORD_U"
  ON "CAD_KEYWORD" ( 
    "COMM_ID", 
    "KEYWORD");
CREATE INDEX "CK_KEYWORD_I"
  ON "CAD_KEYWORD" ( 
    "KEYWORD");
ALTER TABLE "CAD_KEYWORD" ADD ( 
  CONSTRAINT "CK_RECORD_U" 
    UNIQUE ( "COMM_ID", "KEYWORD") 
    USING INDEX "CK_RECORD_U" 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_KEYWORD" ADD ( 
  CONSTRAINT "CK_KEYWORD_NN" 
    CHECK ( "KEYWORD" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_KEYWORD" ADD ( 
  CONSTRAINT "CK_CID_NN" 
    CHECK ( "COMM_ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
-- ****** Object: Table EMA_ADMIN.CAD_COMM Script Date: 2010.05.11. 6:27:53 ******
CREATE TABLE "CAD_COMM" (
  "COMM_ID" VARCHAR2(400 BYTE),
  "CATEGORY" NUMBER(1,0) DEFAULT 0,
  "LINKED" NUMBER(1,0) DEFAULT 0,
  "LINK" VARCHAR2(400 BYTE),
  "CONTENT" CLOB,
  "THREAD_ID" VARCHAR2(400 BYTE),
  "KEYWORDS" VARCHAR2(1000 BYTE));
CREATE UNIQUE INDEX "C_CID_PK"
  ON "CAD_COMM" ( 
    "COMM_ID");
ALTER TABLE "CAD_COMM" ADD ( 
  CONSTRAINT "C_CID_PK" 
    PRIMARY KEY ( "COMM_ID") 
    USING INDEX "C_CID_PK" 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_COMM" ADD ( 
  CONSTRAINT "C_THREAD_ID_NN" 
    CHECK ( "THREAD_ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_COMM" ADD ( 
  CONSTRAINT "C_LINKED_NN" 
    CHECK ( "LINKED" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_COMM" ADD ( 
  CONSTRAINT "C_CAT_NN" 
    CHECK ( "CATEGORY" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_COMM" ADD ( 
  CONSTRAINT "C_CID_NN" 
    CHECK ( "COMM_ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
-- ****** Object: Table EMA_ADMIN.CAD_TAG Script Date: 2010.05.11. 6:27:53 ******
CREATE TABLE "CAD_TAG" (
  "COMM_ID" VARCHAR2(400 BYTE),
  "TAG_ID" VARCHAR2(400 BYTE));
CREATE UNIQUE INDEX "CT_RECORD_U"
  ON "CAD_TAG" ( 
    "COMM_ID", 
    "TAG_ID");
CREATE INDEX "CT_TID_I"
  ON "CAD_TAG" ( 
    "TAG_ID");
ALTER TABLE "CAD_TAG" ADD ( 
  CONSTRAINT "CT_RECORD_U" 
    UNIQUE ( "COMM_ID", "TAG_ID") 
    USING INDEX "CT_RECORD_U" 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_TAG" ADD ( 
  CONSTRAINT "CT_TID_NN" 
    CHECK ( "TAG_ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_TAG" ADD ( 
  CONSTRAINT "CT_CID_NN" 
    CHECK ( "COMM_ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
-- ****** Object: Table EMA_ADMIN.CAS_TAGGINGRULE Script Date: 2010.05.11. 6:27:53 ******
CREATE TABLE "CAS_TAGGINGRULE" (
  "RULE_ID" VARCHAR2(60 BYTE),
  "STATUS" NUMBER(1,0) DEFAULT 1,
  "NAME" VARCHAR2(400 BYTE),
  "TAG" VARCHAR2(400 BYTE),
  "QUERY" CLOB,
  "CUSTOM" NUMBER(1,0) DEFAULT 0);
CREATE UNIQUE INDEX "TR_RID_U"
  ON "CAS_TAGGINGRULE" ( 
    "RULE_ID");
ALTER TABLE "CAS_TAGGINGRULE" ADD ( 
  CONSTRAINT "TR_RID_U" 
    UNIQUE ( "RULE_ID") 
    USING INDEX "TR_RID_U" 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAS_TAGGINGRULE" ADD ( 
  CONSTRAINT "TR_CUSTOM_NN" 
    CHECK ( "CUSTOM" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAS_TAGGINGRULE" ADD ( 
  CONSTRAINT "TR_QUERY_NN" 
    CHECK ( "QUERY" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAS_TAGGINGRULE" ADD ( 
  CONSTRAINT "TR_TAG_NN" 
    CHECK ( "TAG" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAS_TAGGINGRULE" ADD ( 
  CONSTRAINT "TR_NAME_NN" 
    CHECK ( "NAME" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAS_TAGGINGRULE" ADD ( 
  CONSTRAINT "TR_STATUS_NN" 
    CHECK ( "STATUS" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAS_TAGGINGRULE" ADD ( 
  CONSTRAINT "TR_RID_NN" 
    CHECK ( "RULE_ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
-- ****** Object: Table EMA_ADMIN.CAD_PARTICIPANTADDRESS Script Date: 2010.05.11. 6:27:54 ******
CREATE TABLE "CAD_PARTICIPANTADDRESS" (
  "PARTICIPANT_ID" VARCHAR2(400 BYTE),
  "ADDRESS" VARCHAR2(100 BYTE),
  "CATEGORY" NUMBER(1,0) DEFAULT 0);
CREATE UNIQUE INDEX "PA_ADDRESS_U"
  ON "CAD_PARTICIPANTADDRESS" ( 
    "ADDRESS");
ALTER TABLE "CAD_PARTICIPANTADDRESS" ADD ( 
  CONSTRAINT "PA_ADDRESS_U" 
    UNIQUE ( "ADDRESS") 
    USING INDEX "PA_ADDRESS_U" 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_PARTICIPANTADDRESS" ADD ( 
  CONSTRAINT "PA_CAT_NN" 
    CHECK ( "CATEGORY" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_PARTICIPANTADDRESS" ADD ( 
  CONSTRAINT "PA_ADDRESS_NN" 
    CHECK ( "ADDRESS" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_PARTICIPANTADDRESS" ADD ( 
  CONSTRAINT "PA_PID_NN" 
    CHECK ( "PARTICIPANT_ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
-- ****** Object: Table EMA_ADMIN.CAD_ATTACHMENT Script Date: 2010.05.11. 6:27:54 ******
CREATE TABLE "CAD_ATTACHMENT" (
  "ATTACHMENT_ID" VARCHAR2(400 BYTE),
  "CONTENT" BLOB,
  "COMM_ID" VARCHAR2(400 BYTE),
  "FILE_NAME" VARCHAR2(400 BYTE),
  "CONTENT_TYPE" VARCHAR2(400 BYTE));
CREATE UNIQUE INDEX "ATT_AID_U"
  ON "CAD_ATTACHMENT" ( 
    "ATTACHMENT_ID");
CREATE INDEX "ATT_CID_I"
  ON "CAD_ATTACHMENT" ( 
    "COMM_ID");
ALTER TABLE "CAD_ATTACHMENT" ADD ( 
  CONSTRAINT "ATT_CT_NN" 
    CHECK ( "CONTENT_TYPE" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_ATTACHMENT" ADD ( 
  CONSTRAINT "ATT_CID_NN" 
    CHECK ( "COMM_ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_ATTACHMENT" ADD ( 
  CONSTRAINT "ATT_AID_NN" 
    CHECK ( "ATTACHMENT_ID" IS NOT NULL) 
    ENABLE 
    VALIDATE );
-- ****** Object: Table EMA_ADMIN.CAD_DATE Script Date: 2010.05.11. 6:27:54 ******
CREATE TABLE "CAD_DATE" (
  "DATE_KEY" NUMBER(8,0),
  "YEAR" NUMBER(4,0),
  "MONTH" NUMBER(2,0),
  "DAY" NUMBER(2,0),
  "QUARTER" NUMBER(1,0),
  "WORKDAY" NUMBER(1,0) DEFAULT 1,
  "DAY_OF_WEEK" NUMBER(1,0));
CREATE UNIQUE INDEX "D_DKEY_PK"
  ON "CAD_DATE" ( 
    "DATE_KEY");
ALTER TABLE "CAD_DATE" ADD ( 
  CONSTRAINT "D_DKEY_PK" 
    PRIMARY KEY ( "DATE_KEY") 
    USING INDEX "D_DKEY_PK" 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_DATE" ADD ( 
  CONSTRAINT "D_DAY_NN" 
    CHECK ( "DAY" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_DATE" ADD ( 
  CONSTRAINT "D_MON_NN" 
    CHECK ( "MONTH" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_DATE" ADD ( 
  CONSTRAINT "D_YEAR_NN" 
    CHECK ( "YEAR" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_DATE" ADD ( 
  CONSTRAINT "D_DKEY_NN" 
    CHECK ( "DATE_KEY" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_DATE" ADD ( 
  CONSTRAINT "D_DOW_NN" 
    CHECK ( "DAY_OF_WEEK" IS NOT NULL) 
    ENABLE 
    VALIDATE );
-- ****** Object: Table EMA_ADMIN.CAD_TIME Script Date: 2010.05.11. 6:27:54 ******
CREATE TABLE "CAD_TIME" (
  "TIME_KEY" NUMBER(6,0),
  "HOUR" NUMBER(2,0),
  "MINUTE" NUMBER(2,0),
  "SECOND" NUMBER(2,0),
  "TIME_OF_DAY" NUMBER);
CREATE UNIQUE INDEX "T_TKEY_PK"
  ON "CAD_TIME" ( 
    "TIME_KEY");
ALTER TABLE "CAD_TIME" ADD ( 
  CONSTRAINT "T_SEC_NN" 
    CHECK ( "SECOND" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_TIME" ADD ( 
  CONSTRAINT "T_MIN_NN" 
    CHECK ( "MINUTE" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_TIME" ADD ( 
  CONSTRAINT "T_HOUR_NN" 
    CHECK ( "HOUR" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_TIME" ADD ( 
  CONSTRAINT "T_TKEY_NN" 
    CHECK ( "TIME_KEY" IS NOT NULL) 
    ENABLE 
    VALIDATE );
ALTER TABLE "CAD_TIME" ADD ( 
  CONSTRAINT "T_TKEY_PK" 
    PRIMARY KEY ( "TIME_KEY") 
    USING INDEX "T_TKEY_PK" 
    ENABLE 
    VALIDATE );
