;
;
ALTER TABLE CAD_SUBCOMM DISABLE CONSTRAINT SC_FK_COMM;
ALTER TABLE CAD_SUBCOMM DISABLE CONSTRAINT SC_FK_TO;
ALTER TABLE CAD_SUBCOMM DISABLE CONSTRAINT SC_FK_FROM;
ALTER TABLE CAD_SUBCOMM DISABLE CONSTRAINT SC_FK_TIME;
ALTER TABLE CAD_SUBCOMM DISABLE CONSTRAINT SC_FK_DATE;
ALTER TABLE CAD_SUBCOMM DISABLE CONSTRAINT SC_FK_THREAD;

TRUNCATE TABLE CAD_SUBCOMM;
TRUNCATE TABLE CAD_COMM;
TRUNCATE TABLE CAD_DATE;
TRUNCATE TABLE CAD_TIME;
TRUNCATE TABLE CAD_THREAD;

TRUNCATE TABLE CAD_PARTICIPANTRELATION;
TRUNCATE TABLE CAD_PARTICIPANTADDRESS;
DELETE FROM CAD_PARTICIPANT WHERE STATUS=0;

TRUNCATE TABLE CAD_TAG;
TRUNCATE TABLE CAD_KEYWORD;

TRUNCATE TABLE CAD_RAWDATA;

ALTER TABLE CAD_SUBCOMM ENABLE CONSTRAINT SC_FK_COMM;
ALTER TABLE CAD_SUBCOMM ENABLE CONSTRAINT SC_FK_TO;
ALTER TABLE CAD_SUBCOMM ENABLE CONSTRAINT SC_FK_FROM;
ALTER TABLE CAD_SUBCOMM ENABLE CONSTRAINT SC_FK_TIME;
ALTER TABLE CAD_SUBCOMM ENABLE CONSTRAINT SC_FK_DATE;
ALTER TABLE CAD_SUBCOMM ENABLE CONSTRAINT SC_FK_THREAD;
