;
TRUNCATE TABLE CAD_COMM;
TRUNCATE TABLE CAD_SUBCOMM;
TRUNCATE TABLE CAD_TAG;
TRUNCATE TABLE CAD_KEYWORD;
TRUNCATE TABLE CAD_THREAD;
TRUNCATE TABLE CAD_PARTICIPANTADDRESS;

DELETE FROM CAD_PARTICIPANT WHERE STATUS=0;
UPDATE CAD_RAWDATA SET STATUS=0, COMM_ID=NULL;